apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kepler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
  name: keplerrr5m
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kepler
    weight: 100
status: {}
