apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kepler-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kepler-operator
    app.kubernetes.io/part-of: kepler
  name: kepler-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kepler-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kepler-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vimalkum-tenant/kepler/kepler-operator@sha256:6bf9a07bc410b9a7723977fec3c730dec2a4dd9eb4e46853d9af09d99760db2e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
